[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
semver = "1.0"

[dependencies]  # Existing dependencies...
tokio = { version = "1.42.0", features = ["full"] }
swiftide = { version = "0.16.0", features = ["...existing features..."] }
...other_existing_dependencies...
