[package]
name = "kwaak"
version = "0.1.0"
edition = "2021"
categories = ["development-tools", "command-line-utilities"]
readme = "README.md"
repository = "https://github.com/bosun-ai/kwaak"
keywords = ["terminal", "swiftide", "tui", "ai", "llm"]
description = "Run a team of autonomous agents on your code, right from your terminal"
license = "MIT"

[dependencies]
anyhow = "1.0.88"
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
tokio = { version = "1.40.0", features = ["full"] }
strum = "0.26.3"
strum_macros = "0.26.4"
swiftide = { version = "0.14.4", features = [
  "lancedb",
  "openai",
  "tree-sitter",
  "redb",
  "swiftide-agents",

] }
swiftide-macros = { version = "0.14.4" }
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.133"
secrecy = { version = "0.10.2", features = ["serde"] }
tracing = "0.1.40"
async-openai = "0.26.0"
dirs = "5.0.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
tracing-opentelemetry = { version = "0.28.0", optional = true }
opentelemetry_sdk = { version = "0.27.0", optional = true, features = [
  "rt-tokio",
] }
opentelemetry = { version = "0.27.0", optional = true }
opentelemetry-otlp = { version = "0.27.0", optional = true, features = [
  "tonic",
] }

derive_more = { version = "1.0.0", features = ["full"] }
# tui-markdown = { git = "https://github.com/timonv/tui-markdown.git", branch = "code-highlighting", features = [
#   "highlight-code",
# ] }
tui-markdown = "0.3.0"
uuid = { version = "1.10.0", features = ["v4"] }
derive_builder = "0.20.2"
tui-logger = { features = ["tracing-support"], version = "0.14" }
# Only needed for tui-logger filtering
log = "0.4"
throbber-widgets-tui = "0.8.0"
bollard = "0.18.1"
tokio-tar = "0.3.1"
ignore = "0.4.23"
async-trait = "0.1.83"
url = "2.5.3"
octocrab = "0.42.0"
indoc = "2.0.5"
tavily = "1.0.0"
regex = "1.11.1"
clap = { version = "4.5.21", features = ["derive"] }
tera = "1.20.0"
lazy_static = "1.5.0"
rust-embed = { version = "8.5.0", features = ["debug-embed"] }

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
insta = "1.41.1"
tempfile = "3.14.0"

[lints.rust]
unsafe_code = "forbid"
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage,coverage_nightly)',
] }

[lints.clippy]
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# blocks_in_conditions = "allow"
# must_use_candidate = "allow"
module_name_repetitions = "allow"
# missing_fields_in_debug = "allow"
# # Should be fixed asap
multiple_crate_versions = "allow"
# Prefer to keep this explicit as it avoids accidental moves
needless_borrow = "allow"

[features]
default = ["otel"]
"test-layout" = []
"otel" = [
  "dep:tracing-opentelemetry",
  "dep:opentelemetry_sdk",
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
]

[patch.crates-io]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
# swiftide = { git = "https://github.com/bosun-ai/swiftide", branch = "feat/swiftide-agents" }
# swiftide-macros = { git = "https://github.com/bosun-ai/swiftide", branch = "feat/swiftide-agents" }
# swiftide = { path = "../swiftide/swiftide" }
# swiftide-macros = { path = "../swiftide/swiftide-macros" }
