[package]
name = "kwaak"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
assert_cmd = "*"
predicates = "*"
tempfile = "*"
test-log = "*"
anyhow = "*"
ratatui = "*"
clap = "*"
tracing = "*"
crossterm = "*"
swiftide = "*"
uuid = "*"
regex = "*"
serde = "*"
tavily = "*"
toml = "*"
dirs = "*"
