[package]
name = "kwaak"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
assert_cmd = "*"
predicates = "*"
tempfile = "*"
test-log = "*"
anyhow = "*"
ratatui = "*"
clap = "*"
tracing = "*"
crossterm = "*"
swiftide = { version = "*", features = ["swiftide-agents"] }
uuid = "*"
regex = "*"
serde = "*"
tavily = "*"
toml = "*"
dirs = "*"
tokio = "*"
secrecy = "*"
strum = "*"
tui-logger = "*"
tui_textarea = "*"
ratatui-splash-screen = "*"
octocrab = "*"
reqwest = "*"
serde_json = "*"
url = "*"
tracing-subscriber = "*"
indoc = "*"
num_cpus = "*"
tui-markdown = "*"
htmd = "*"
