[package]
name = "kwaak"
version = "0.1.0"
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
futures-util = "0.3"
swiftide = { path = "../swiftide" }
indoc = "0.3"
mockall = "0.10"
mockall_derive = "0.10"

[dev-dependencies]
mockall = "0.10.2"

# Other dependencies omitted for brevity
