services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      # First port is the web ui
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
