language = "rust"
tavily_api_key = "env:TAVILY_API_KEY"
tool_executor = "docker"
otel_enabled = true

[commands]
test = "RUST_LOG=kwaak=debug,swiftide=debug RUST_BACKTRACE=1 cargo nextest run --no-fail-fast --color=never"
coverage = "cargo llvm-cov nextest --no-clean --summary-only"
lint_and_fix = "cargo clippy --fix --allow-dirty --allow-staged; cargo fmt"

[github]
owner = "bosun-ai"
repository = "kwaak"
main_branch = "master"
token = "env:GITHUB_TOKEN"

[llm.indexing]
provider = "Ollama"
prompt_model = "llama3.2:1b"

[llm.query]
provider = "Ollama"
prompt_model = "llama3.2"

[llm.embedding]
provider = "Ollama"
embedding_model = { name = "bge-m3", vector_size = 1024 }

[docker]
dockerfile = "Dockerfile"
