language = "rust"
tavily_api_key = "env:TAVILY_API_KEY"
tool_executor = "docker"

[commands]
test = "RUST_LOG=kwaak=debug,swiftide=debug RUST_BACKTRACE=1 cargo test --no-fail-fast --color=never"
coverage = "cargo tarpaulin --skip-clean --target-dir target/debug --engine llvm"
lint_and_fix = "cargo clippy --fix --allow-dirty --allow-staged && cargo fmt"

[github]
owner = "bosun-ai"
repository = "kwaak"
main_branch = "master"
token = "env:GITHUB_TOKEN"

[llm.indexing]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o-mini"

[llm.query]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o"

[llm.embedding]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
embedding_model = "text-embedding-3-large"

[docker]
dockerfile = "Dockerfile"
