name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_LOG: debug
  RUST_BACKTRACE: 1
  TAVILY_API_KEY: noop
  KWAAK_OPENAI_API_KEY: noop
  KWAAK_GITHUB_TOKEN: noop

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Install deps
        run: sudo apt install libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev ripgrep fd-find
      # Temporary fix until docker runs properly in ci
      - name: copy fdfind
        run: sudo cp /usr/bin/fdfind /usr/bin/fd
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov nextest --all-features --lcov --output-path lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2
